;;; KeyBorads
(defun open-my-init-file()
  "No Document."
  (interactive)
  (find-file "~/.emacs.d/init.el"))

(global-set-key (kbd "C-<tab>") 'sort-tab-select-next-tab)
(global-set-key (kbd "C-<iso-lefttab>") 'sort-tab-select-prev-tab)
(global-set-key (kbd "C-<return>") 'sort-tab-close-current-tab)
(global-set-key (kbd "C-1") 'sort-tab-select-visible-tab)
(global-set-key (kbd "C-2") 'sort-tab-select-visible-tab)
(global-set-key (kbd "C-3") 'sort-tab-select-visible-tab)
(global-set-key (kbd "C-4") 'sort-tab-select-visible-tab)
(global-set-key (kbd "C-5") 'sort-tab-select-visible-tab)
(global-set-key (kbd "C-6") 'sort-tab-select-visible-tab)
(global-set-key (kbd "C-7") 'sort-tab-select-visible-tab)
(global-set-key (kbd "C-8") 'sort-tab-select-visible-tab)
(global-set-key (kbd "C-9") 'sort-tab-select-visible-tab)
(global-set-key (kbd "C-0") 'sort-tab-select-visible-tab)

(global-set-key (kbd "RET") 'newline-and-indent)
(global-set-key (kbd "<f6>") 'dashboard-mode)
(global-set-key (kbd "M-d") nil)
(define-prefix-command 'meta-d-map)
(global-set-key (kbd "M-d f d o") 'open-my-init-file)
(global-set-key (kbd "M-d w /") 'split-window-right)
(global-set-key (kbd "M-d w -") 'split-window-below)
(global-set-key (kbd "M-d b d") 'kill-this-buffer)
(global-set-key (kbd "M-d b w d") 'kill-buffer-and-window)
(global-set-key (kbd "M-d w h  +") 'enlarge-window-horizontally)
(global-set-key (kbd "M-d w h -") 'shrink-window-horizontally)
(global-set-key (kbd "M-d w c +") 'enlarge-window)
(global-set-key (kbd "M-d w c -") 'shrink-window)
(global-set-key (kbd "M-d w d") 'delete-window)
(global-set-key (kbd "M-d f t") 'treemacs)
(global-set-key (kbd "M-d f d r") 'eval-buffer)
(global-set-key (kbd "M-d l") 'goto-line)
(global-set-key (kbd "M-d e o") 'eaf-open)
(global-set-key (kbd "M-d e b") 'eaf-open-browser-with-history)
(global-set-key (kbd "M-d c a") 'format-all-buffer)
(global-set-key (kbd "M-d c l") 'lsp)
(global-set-key (kbd "M-d c c") 'comment-or-uncomment-region)
;; Plugin Keyborads
(global-set-key (kbd "C-a") 'mwim-beginning-of-code-or-line)
(global-set-key (kbd "C-e") 'mwim-end-of-code-or-line)
(global-set-key (kbd "C-s") 'swiper)
(global-set-key (kbd "C-x b") 'ivy-switch-buffer)
(global-set-key (kbd "C-c v") 'ivy-push-view)
(global-set-key (kbd "C-c s") 'ivy-switch-view)
(global-set-key (kbd "C-c V") 'ivy-pop-view)
(global-set-key (kbd "C-x C-@") 'counsel-mark-ring)
(global-set-key (kbd "C-x C-SPC") 'counsel-mark-ring)
(global-set-key (kbd "C-c l s") 'lsp-ivy-workspace-symbol)

(provide 'keys)
;;; keys.el ends here
